### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bkuhl**

### CODE REVIEW

**Comment by bkuhl** [comment]
The build is failing for reasons unrelated to this change, so accepting anyways would be ideal :)

**Comment by bkuhl** [comment]
Going ahead and merging this in since it's only readme changes and the code changes just passed in another branch

**Comment by millidavids** [comment]
Might want to take me out of this organization :)

**Comment by bkuhl** [comment]
You aren't in the organization anymore.. maybe you're still following the repo?

**Pull request merged**
